"""Remembering which window the transcript belongs to.

The macOS build captured the frontmost application when recording stopped and
posted the paste event to *that* process, so a transcript never landed in the
wrong place if the user moved on while the model was still working. It also
refused to paste into BetterVoice itself.

On KDE the compositor can answer both halves: a KWin script reports the active
window when a recording ends, and a second one brings it back before the paste.
Elsewhere there is no way to ask, so the paste goes wherever focus is -- with the
"never paste into ourselves" guard still applied, since Qt always knows that much.
"""

from __future__ import annotations

import json
import logging
import re
import secrets
from dataclasses import dataclass
from typing import Callable

from PyQt6 import QtCore, QtGui

from . import environment, kwin

log = logging.getLogger(__name__)

CAPTURE_SCRIPT = "bettervoice-focus-capture"
RESTORE_SCRIPT = "bettervoice-focus-restore"

#: KWin identifies a window by `internalId`, which is a QUuid and nothing else.
#: The value arrives over a D-Bus method any peer on the session bus can call,
#: and it is interpolated into a script the compositor executes -- so it is
#: checked against the only shape it is ever legitimately allowed to have.
_WINDOW_ID = re.compile(r"\{?[0-9a-fA-F]{8}(?:-[0-9a-fA-F]{4}){3}-[0-9a-fA-F]{12}\}?")


def _is_window_id(value: str) -> bool:
    return bool(_WINDOW_ID.fullmatch(value))

_CAPTURE_SOURCE = """\
// Generated by BetterVoice. Reports the window that was active when a recording
// ended, so the transcript can be returned to it.
var betterVoiceWindow = workspace.activeWindow;
callDBus(
    {service},
    {path},
    {interface},
    "Captured",
    betterVoiceWindow ? "" + betterVoiceWindow.internalId : "",
    betterVoiceWindow ? "" + betterVoiceWindow.resourceClass : "",
    betterVoiceWindow ? "" + betterVoiceWindow.caption : "",
    {nonce}
);
"""

_RESTORE_SOURCE = """\
// Generated by BetterVoice. Brings one window back to the front so the
// transcript is pasted where the user was actually typing.
var betterVoiceTarget = {target};
var betterVoiceList = workspace.windowList ? workspace.windowList() : workspace.clientList();
var betterVoiceFound = false;
for (var i = 0; i < betterVoiceList.length; i++) {{
    if ("" + betterVoiceList[i].internalId === betterVoiceTarget) {{
        workspace.activeWindow = betterVoiceList[i];
        betterVoiceFound = true;
        break;
    }}
}}
callDBus({service}, {path}, {interface}, "Restored", betterVoiceFound, {nonce});
"""


@dataclass(frozen=True)
class FocusTarget:
    """The window a transcript should go back to."""

    window_id: str
    application: str = ""
    caption: str = ""

    def __bool__(self) -> bool:
        return bool(self.window_id)


def _own_application_names() -> set[str]:
    names = {"bettervoice"}
    desktop = QtGui.QGuiApplication.desktopFileName()
    if desktop:
        names.add(desktop.lower())
        names.add(desktop.rsplit(".", 1)[-1].lower())
    name = QtGui.QGuiApplication.applicationName()
    if name:
        names.add(name.lower())
    return names


def belongs_to_us(application: str) -> bool:
    """Whether a window's application id is one of ours."""

    return application.lower() in _own_application_names()


def focused_own_window() -> QtGui.QWindow | None:
    """The BetterVoice window the user could be typing into, if any.

    The recording overlay is fullscreen and always on top, but transparent for
    input -- nothing can be typed into it, so it must never count as us holding
    focus or a transcript would be refused whenever it is on screen.
    """

    window = QtGui.QGuiApplication.focusWindow()
    if window is None:
        return None
    if window.flags() & QtCore.Qt.WindowType.WindowTransparentForInput:
        return None
    return window


def we_have_focus() -> bool:
    """Whether one of BetterVoice's own windows currently holds focus."""

    return focused_own_window() is not None


class FocusBackend(QtCore.QObject):
    name = "none"

    def capture(self, on_done: Callable[[FocusTarget | None], None]) -> None:
        on_done(None)

    def restore(self, target: FocusTarget | None, on_done: Callable[[bool], None]) -> None:
        on_done(False)

    def stop(self) -> None:
        pass

    @property
    def remembers_target(self) -> bool:
        return False


class NullFocusBackend(FocusBackend):
    """No way to ask; the paste goes wherever focus already is."""


class _CaptureSink(kwin.ExportedObject):
    """The object KWin's scripts call back into.

    These slots are exported on the session bus, where any peer running as the
    user can call them. Only the script we just wrote knows the nonce it was
    generated with, so a call carrying the wrong one did not come from the
    request we are waiting on and is dropped.
    """

    captured = QtCore.pyqtSignal(str, str, str)
    restored = QtCore.pyqtSignal(bool)

    def __init__(self, service: str, path: str) -> None:
        super().__init__(service, path)
        self.nonce = ""

    def _expected(self, nonce: str) -> bool:
        if not self.nonce or not secrets.compare_digest(nonce, self.nonce):
            log.warning("Ignoring a D-Bus call that did not come from our own script")
            return False
        return True

    @QtCore.pyqtSlot(str, str, str, str)
    def Captured(self, window_id: str, application: str, caption: str, nonce: str) -> None:
        if not self._expected(nonce):
            return
        self.captured.emit(window_id, application, caption)

    @QtCore.pyqtSlot(bool, str)
    def Restored(self, found: bool, nonce: str) -> None:
        if not self._expected(nonce):
            return
        self.restored.emit(found)


class KWinFocusBackend(FocusBackend):
    name = "kwin"

    #: A capture is a couple of D-Bus round trips; well past this something is wrong.
    TIMEOUT_MS = 2_000

    def __init__(self) -> None:
        super().__init__()
        self._sink = _CaptureSink(kwin.unique_service("Focus"), kwin.unique_path("Focus"))
        self._interface: str | None = None
        self._sink.captured.connect(self._on_captured)
        self._sink.restored.connect(self._on_restored)
        self._capture_callback: Callable[[FocusTarget | None], None] | None = None
        self._restore_callback: Callable[[bool], None] | None = None
        self._timer = QtCore.QTimer(self)
        self._timer.setSingleShot(True)
        self._timer.setInterval(self.TIMEOUT_MS)
        self._timer.timeout.connect(self._on_timeout)

    @staticmethod
    def available() -> bool:
        return environment.is_kde() and kwin.available()

    @property
    def remembers_target(self) -> bool:
        return True

    def _ensure_registered(self) -> bool:
        if self._interface is None:
            self._interface = self._sink.register()
        return self._interface is not None

    def capture(self, on_done: Callable[[FocusTarget | None], None]) -> None:
        if self._capture_callback is not None or not self._ensure_registered():
            on_done(None)
            return
        self._capture_callback = on_done
        source = _CAPTURE_SOURCE.format(**self._script_values())
        if not kwin.load_and_run(CAPTURE_SCRIPT, source):
            self._capture_callback = None
            on_done(None)
            return
        self._timer.start()

    def _script_values(self) -> dict[str, str]:
        """Values for one generated script, each as a JavaScript literal.

        Interpolating into hand-written quotes is how a value that contains one
        stops being a string and starts being code -- in a script the compositor
        runs unsandboxed. ``json.dumps`` emits the quotes itself and escapes
        anything inside them.
        """

        self._sink.nonce = secrets.token_hex(16)
        return {
            "service": json.dumps(self._sink.service),
            "path": json.dumps(self._sink.path),
            "interface": json.dumps(self._interface),
            "nonce": json.dumps(self._sink.nonce),
        }

    def _on_captured(self, window_id: str, application: str, caption: str) -> None:
        self._timer.stop()
        kwin.unload(CAPTURE_SCRIPT)
        callback, self._capture_callback = self._capture_callback, None
        if callback is None:
            return
        if not window_id or belongs_to_us(application):
            # Returning the transcript to our own setup window would be worse
            # than leaving it on the clipboard.
            callback(None)
            return
        if not _is_window_id(window_id):
            # It gets interpolated into a script KWin executes; anything that is
            # not a plain QUuid has no business being there.
            log.warning("Ignoring a window id that is not a UUID")
            callback(None)
            return
        callback(FocusTarget(window_id, application, caption))

    def restore(self, target: FocusTarget | None, on_done: Callable[[bool], None]) -> None:
        if not target or self._restore_callback is not None or not self._ensure_registered():
            on_done(False)
            return
        self._restore_callback = on_done
        source = _RESTORE_SOURCE.format(
            target=json.dumps(target.window_id), **self._script_values()
        )
        if not kwin.load_and_run(RESTORE_SCRIPT, source):
            self._restore_callback = None
            on_done(False)
            return
        self._timer.start()

    def _on_restored(self, found: bool) -> None:
        self._timer.stop()
        kwin.unload(RESTORE_SCRIPT)
        callback, self._restore_callback = self._restore_callback, None
        if callback is not None:
            callback(bool(found))

    def _on_timeout(self) -> None:
        log.info("KWin did not answer a focus request in time")
        for name, callback in (
            (CAPTURE_SCRIPT, self._capture_callback),
            (RESTORE_SCRIPT, self._restore_callback),
        ):
            if callback is not None:
                kwin.unload(name)
        capture, self._capture_callback = self._capture_callback, None
        restore, self._restore_callback = self._restore_callback, None
        if capture is not None:
            capture(None)
        if restore is not None:
            restore(False)

    def stop(self) -> None:
        """Leave no script behind, whether or not this object loaded one."""

        self._timer.stop()
        for name in (CAPTURE_SCRIPT, RESTORE_SCRIPT):
            kwin.unload(name)


def create(preference: str = "auto") -> FocusBackend:
    if preference == "none":
        return NullFocusBackend()
    if preference in {"auto", "", "kwin"} and KWinFocusBackend.available():
        return KWinFocusBackend()
    return NullFocusBackend()
