"""Global pointer position -- the Linux answer to ``CGEvent(source:).location``.

Wayland deliberately hides the pointer from applications, so there is no single
call that works everywhere. Three backends cover the realistic cases:

``kwin``
    KDE Plasma (Wayland *and* X11). A tiny KWin script polls
    ``workspace.cursorPos`` and pushes it back over D-Bus. Exact, and it needs no
    extra permissions -- the compositor is doing the reading.
``x11``
    ``XQueryPointer``. Exact on any X11 session.
``evdev``
    Integrates relative motion straight from ``/dev/input``. Works anywhere the
    user can read those devices, but pointer acceleration means the position is
    an estimate rather than the compositor's own.

When none of them is available the app still records; only the circle-to-capture
gesture goes quiet, and the setup window explains how to turn it back on.
"""

from __future__ import annotations

import importlib.util
import json
import logging
import secrets
import threading
from typing import Callable

from PyQt6 import QtCore

from .. import APP_NAME
from . import environment, input_devices, kwin

log = logging.getLogger(__name__)

PointerCallback = Callable[[float, float], None]

_KWIN_SCRIPT_NAME = "bettervoice-pointer"
_KWIN_SCRIPT_TEMPLATE = """\
// Generated by {app}. Polls the compositor's own cursor position and hands it
// back over D-Bus so BetterVoice can follow circles drawn anywhere on screen.
var betterVoiceTimer = new QTimer();
betterVoiceTimer.interval = {interval};
betterVoiceTimer.timeout.connect(function () {{
    var position = workspace.cursorPos;
    callDBus(
        {service},
        {path},
        {interface},
        "Moved",
        position.x,
        position.y,
        {nonce}
    );
}});
betterVoiceTimer.start();
"""


class PointerBackend(QtCore.QObject):
    """Base class. ``moved`` carries global screen coordinates in pixels."""

    moved = QtCore.pyqtSignal(float, float)
    name = "none"
    accurate = True

    def start(self) -> None:  # pragma: no cover - overridden
        pass

    def stop(self) -> None:  # pragma: no cover - overridden
        pass

    @property
    def unavailable_reason(self) -> str | None:
        return None


class NullPointerBackend(PointerBackend):
    name = "none"

    def __init__(self, reason: str) -> None:
        super().__init__()
        self._reason = reason

    @property
    def unavailable_reason(self) -> str | None:
        return self._reason


class _PointerSink(kwin.ExportedObject):
    """The D-Bus object the KWin script calls into.

    Exported on the session bus, so any peer running as the user can call it.
    Synthetic pointer positions would steer the circle gesture into capturing
    the screen on someone else's cue, so a call has to carry the nonce the
    running script was generated with.
    """

    moved = QtCore.pyqtSignal(float, float)

    def __init__(self, service: str, path: str) -> None:
        super().__init__(service, path)
        self.nonce = ""

    @QtCore.pyqtSlot(int, int, str)
    def Moved(self, x: int, y: int, nonce: str) -> None:
        if not self.nonce or not secrets.compare_digest(nonce, self.nonce):
            return
        self.moved.emit(float(x), float(y))


class KWinPointerBackend(PointerBackend):
    name = "kwin"

    def __init__(self, interval_ms: int = 16) -> None:
        super().__init__()
        self._interval = interval_ms
        self._sink = _PointerSink(kwin.unique_service("Pointer"), kwin.unique_path("Pointer"))
        self._sink.moved.connect(self.moved)
        self._loaded = False

    @staticmethod
    def available() -> bool:
        return environment.is_kde() and kwin.available()

    @property
    def unavailable_reason(self) -> str | None:
        # Never claim to be tracking the pointer when the bridge failed to come
        # up: the trail would simply never appear, with no explanation.
        return self._sink.failure

    def start(self) -> None:
        if self._loaded:
            return
        interface = self._sink.register()
        if interface is None:
            return
        self._sink.nonce = secrets.token_hex(16)
        source = _KWIN_SCRIPT_TEMPLATE.format(
            app=APP_NAME,
            interval=int(self._interval),
            service=json.dumps(self._sink.service),
            path=json.dumps(self._sink.path),
            interface=json.dumps(interface),
            nonce=json.dumps(self._sink.nonce),
        )
        self._loaded = kwin.load_and_run(_KWIN_SCRIPT_NAME, source)

    def stop(self) -> None:
        # Unload unconditionally. The script name is fixed, so a previous run
        # that crashed -- or a second instance -- can leave one loaded that this
        # object never knew about, and unloading a script that is not there is
        # harmless.
        kwin.unload(_KWIN_SCRIPT_NAME)
        self._loaded = False


class X11PointerBackend(PointerBackend):
    name = "x11"

    def __init__(self, interval_ms: int = 16) -> None:
        super().__init__()
        self._interval = interval_ms
        self._timer = QtCore.QTimer(self)
        self._timer.setTimerType(QtCore.Qt.TimerType.PreciseTimer)
        self._timer.setInterval(interval_ms)
        self._timer.timeout.connect(self._sample)
        self._display = None
        self._root = None

    @staticmethod
    def available() -> bool:
        if not environment.is_x11():
            return False
        return importlib.util.find_spec("Xlib") is not None

    def start(self) -> None:
        from Xlib import display as xdisplay  # imported here so X11 stays optional

        self._display = xdisplay.Display()
        self._root = self._display.screen().root
        self._timer.start()

    def stop(self) -> None:
        self._timer.stop()
        if self._display is not None:
            try:
                self._display.close()
            except Exception:  # pragma: no cover - display already gone
                pass
        self._display = None
        self._root = None

    def _sample(self) -> None:
        if self._root is None:
            return
        try:
            pointer = self._root.query_pointer()
        except Exception as error:  # pragma: no cover - X server disappeared
            log.warning("Pointer query failed: %s", error)
            self.stop()
            return
        self.moved.emit(float(pointer.root_x), float(pointer.root_y))


class EvdevPointerBackend(PointerBackend):
    """Integrates relative motion from readable ``/dev/input`` devices."""

    name = "evdev"
    accurate = False

    def __init__(self, bounds: tuple[int, int, int, int] = (0, 0, 1920, 1080)) -> None:
        super().__init__()
        self._bounds = bounds
        self._thread: threading.Thread | None = None
        self._stop = threading.Event()
        self._x = (bounds[0] + bounds[2]) / 2
        self._y = (bounds[1] + bounds[3]) / 2

    def set_bounds(self, bounds: tuple[int, int, int, int]) -> None:
        self._bounds = bounds
        self._x = min(max(self._x, bounds[0]), bounds[2])
        self._y = min(max(self._y, bounds[1]), bounds[3])

    @staticmethod
    def readable_devices() -> list[str]:
        return input_devices.readable(input_devices.pointers())

    @staticmethod
    def available() -> bool:
        return bool(EvdevPointerBackend.readable_devices()) and (
            importlib.util.find_spec("evdev") is not None
        )

    @property
    def unavailable_reason(self) -> str | None:
        if importlib.util.find_spec("evdev") is None:
            return "The 'evdev' package is not installed; run: pip install evdev"
        # Even with every device readable the position is an estimate, because
        # integrating raw motion cannot know the pointer acceleration curve.
        return input_devices.partial_access_warning(
            "pointing device", input_devices.pointers()
        )

    def start(self) -> None:
        if self._thread is not None:
            return
        self._stop.clear()
        self._thread = threading.Thread(target=self._run, name="bettervoice-pointer", daemon=True)
        self._thread.start()

    def stop(self) -> None:
        self._stop.set()
        thread, self._thread = self._thread, None
        if thread is not None:
            thread.join(timeout=1)

    def _run(self) -> None:
        import selectors

        import evdev

        devices = []
        for path in self.readable_devices():
            try:
                devices.append(evdev.InputDevice(path))
            except OSError:
                continue
        if not devices:
            return
        selector = selectors.DefaultSelector()
        for device in devices:
            selector.register(device, selectors.EVENT_READ)
        try:
            while not self._stop.is_set():
                for key, _ in selector.select(timeout=0.2):
                    device = key.fileobj
                    try:
                        events = list(device.read())
                    except OSError:
                        continue
                    changed = False
                    for event in events:
                        if event.type != evdev.ecodes.EV_REL:
                            continue
                        if event.code == evdev.ecodes.REL_X:
                            self._x += event.value
                            changed = True
                        elif event.code == evdev.ecodes.REL_Y:
                            self._y += event.value
                            changed = True
                    if not changed:
                        continue
                    left, top, right, bottom = self._bounds
                    self._x = min(max(self._x, left), right)
                    self._y = min(max(self._y, top), bottom)
                    self.moved.emit(self._x, self._y)
        finally:
            selector.close()
            for device in devices:
                device.close()


def create(preference: str = "auto") -> PointerBackend:
    """Pick the best pointer backend, honouring an explicit config override."""

    candidates: list[tuple[str, Callable[[], bool], Callable[[], PointerBackend]]] = [
        ("kwin", KWinPointerBackend.available, KWinPointerBackend),
        ("x11", X11PointerBackend.available, X11PointerBackend),
        ("evdev", EvdevPointerBackend.available, EvdevPointerBackend),
    ]

    if preference not in {"auto", "none"}:
        for name, available, factory in candidates:
            if name != preference:
                continue
            if available():
                return factory()
            return NullPointerBackend(
                f"The {name} pointer backend is not usable in this session."
            )
        return NullPointerBackend(f"Unknown pointer backend {preference!r}.")

    if preference == "none":
        return NullPointerBackend("Circle-to-capture is switched off in settings.")

    for _, available, factory in candidates:
        if available():
            return factory()

    if environment.is_wayland():
        reason = (
            "Wayland does not hand the pointer position to applications. "
            "On KDE Plasma this works automatically; elsewhere, add your user to "
            "the 'input' group to let BetterVoice read pointer motion directly."
        )
    else:
        reason = "No pointer source is available in this session."
    return NullPointerBackend(reason)
